name: deploy-pelican

on:
  # Trigger the workflow on push on main branch,
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install Stork
        run: |
          wget https://files.stork-search.net/releases/v1.6.0/stork-ubuntu-20-04
          chmod +x stork-ubuntu-20-04
          mv stork-ubuntu-20-04 /usr/local/bin/stork
      - name: Install dependencies and theme
        run: |
          echo "Install dependencies"
          sudo apt-get update
          sudo apt-get install -y libssl1.1
          pip install -r requirements.txt
      - name: Compile with pelican
        run: |
          pelican content -s publishconf.py
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.PUBLISH_TOKEN }}
          publish_branch: gh-pages
          publish_dir: blog-output/
          force_orphan: true
